name: Webhook-Test

on: [push, pull_request]

jobs:
  webhook-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '17'
    - name: Run test
      run: mvn package
    
