name: Webhook-Test

on: [push]

jobs:
  webhook-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v3
      with:
        distribution: 'oracle'
        java-version: '19'
    - name: Run test
      run: mvn package
    
